build:
  version: "2.0"

employee:
  message: "Welcome to Employee related QA APIs "
  contactDetails:
    name: "Smitha Ray - QA Lead"
    email: "smitha@emp.com"
  onCallSupport:
    - (666) 265-3765
    - (666) 734-8371